name: Chalice Deploy for beta
on:
  push:
    branches:
      - main
    paths:
      - 'backend/libra-api/**'

jobs:
  chalice:
    name: Chalice Deploy for beta
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::518773205675:role/libra-base-githubactions-role
          aws-region: ap-northeast-1

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        working-directory: backend/libra-api
        run: |
          python -m pip install --upgrade pip
          pip install chalice boto3

      - name: Chalice Deploy
        id: deploy
        working-directory: backend/libra-api
        run: |
          chalice deploy --stage=beta
